package storage

import (
	"context"
	"database/sql"
	"testing"
	"time"
)

// ---------------------------------------------------------------------------
// Unit tests for functions that can run without a real DB
// (pure logic / helper behaviour).
// ---------------------------------------------------------------------------

// TestPromoteHelperSQL verifies the SQL generated by promote* helpers is valid Go
// (compilation proves the strings are correct). No DB required.
func TestPromoteHelperSQL(t *testing.T) {
	// We cannot call promotePrimaryAddress without a *sql.Tx, but we can at
	// least verify the function signatures are correct and that we're passing
	// the right types.
	ctx := context.Background()
	var tx *sql.Tx // nil – just for type-checking at test time

	// These would panic at runtime (nil tx), so we only run this in a type-
	// checking guard: if the functions didn't exist or had wrong signatures,
	// the file wouldn't compile. We use a conditional that can never be true.
	if false {
		_ = promotePrimaryAddress(ctx, tx, "pubkey", 0)
		_ = promoteNIP05Address(ctx, tx, "pubkey", 0)
		_ = openOwnership(ctx, tx, "user", "domain", "pubkey")
		_ = closeOwnership(ctx, tx, "user", "domain", "pubkey")
		_ = copyLightningConfig(ctx, tx, 1, 2)
	}
}

// ---------------------------------------------------------------------------
// AuditListFilter query-builder tests
// ---------------------------------------------------------------------------

func TestAuditListFilterDefaults(t *testing.T) {
	f := AuditListFilter{}
	// ListAudit caps limit to 100 when unset.
	// Simulate what ListAudit does:
	limit := f.Limit
	if limit <= 0 || limit > 500 {
		limit = 100
	}
	if limit != 100 {
		t.Errorf("expected default limit 100, got %d", limit)
	}
}

func TestAuditListFilterMaxLimit(t *testing.T) {
	f := AuditListFilter{Limit: 9999}
	limit := f.Limit
	if limit <= 0 || limit > 500 {
		limit = 100
	}
	if limit != 100 {
		t.Errorf("expected capped limit 100 for input 9999, got %d", limit)
	}
}

func TestAuditListFilterValidLimit(t *testing.T) {
	f := AuditListFilter{Limit: 42}
	limit := f.Limit
	if limit <= 0 || limit > 500 {
		limit = 100
	}
	if limit != 42 {
		t.Errorf("expected limit 42, got %d", limit)
	}
}

// ---------------------------------------------------------------------------
// Ownership interval model tests (pure logic)
// ---------------------------------------------------------------------------

// TestOwnershipIntervalModel validates the expected temporal query semantics
// without hitting a DB: an ownership interval covers [valid_from, valid_to).
func TestOwnershipIntervalModel(t *testing.T) {
	type interval struct {
		ValidFrom time.Time
		ValidTo   *time.Time // nil = still open
	}

	inInterval := func(iv interval, t time.Time) bool {
		if t.Before(iv.ValidFrom) {
			return false
		}
		if iv.ValidTo != nil && !t.Before(*iv.ValidTo) {
			return false
		}
		return true
	}

	base := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	closeTime := base.Add(24 * time.Hour)

	open := interval{ValidFrom: base, ValidTo: nil}
	closed := interval{ValidFrom: base, ValidTo: &closeTime}

	// Open interval: contains everything after ValidFrom.
	if !inInterval(open, base.Add(time.Second)) {
		t.Error("open interval should contain time after ValidFrom")
	}
	if !inInterval(open, base.Add(100*24*time.Hour)) {
		t.Error("open interval should contain far future time")
	}
	if inInterval(open, base.Add(-time.Second)) {
		t.Error("open interval should not contain time before ValidFrom")
	}

	// Closed interval: [ValidFrom, ValidTo).
	if !inInterval(closed, base.Add(time.Second)) {
		t.Error("closed interval should contain time between bounds")
	}
	if inInterval(closed, closeTime) { // strictly before valid_to
		t.Error("closed interval should not contain time == valid_to (exclusive upper bound)")
	}
	if inInterval(closed, closeTime.Add(time.Second)) {
		t.Error("closed interval should not contain time after valid_to")
	}
}

// ---------------------------------------------------------------------------
// AuditEntry struct / writeAudit contract tests
// ---------------------------------------------------------------------------

// TestAuditEntrySubjectPubkeyField ensures SubjectPubkey is declared on the struct.
func TestAuditEntrySubjectPubkeyField(t *testing.T) {
	e := AuditEntry{
		TableName:     "addresses",
		RecordID:      "1",
		Action:        "address.grant",
		ActorPubkey:   "actor",
		SubjectPubkey: "subject",
	}
	if e.SubjectPubkey != "subject" {
		t.Errorf("SubjectPubkey field not set correctly: %s", e.SubjectPubkey)
	}
}

// TestAuditRowSubjectPubkeyField ensures AuditRow carries SubjectPubkey.
func TestAuditRowSubjectPubkeyField(t *testing.T) {
	subj := "abc123"
	r := AuditRow{SubjectPubkey: &subj}
	if r.SubjectPubkey == nil || *r.SubjectPubkey != "abc123" {
		t.Error("AuditRow.SubjectPubkey not set correctly")
	}
}

// ---------------------------------------------------------------------------
// Address struct field tests
// ---------------------------------------------------------------------------

func TestAddressStructFields(t *testing.T) {
	a := Address{
		ID:          1,
		Username:    "alice",
		Domain:      "cloistr.xyz",
		Pubkey:      "abc",
		Active:      true,
		Verified:    true,
		IsPrimary:   true,
		NIP05Active: true,
	}
	if !a.IsPrimary {
		t.Error("IsPrimary not set")
	}
	if !a.NIP05Active {
		t.Error("NIP05Active not set")
	}
}

// TestAddressSummaryFields verifies AddressSummary has the expected fields.
func TestAddressSummaryFields(t *testing.T) {
	s := AddressSummary{
		Username:    "bob",
		Domain:      "cloistr.xyz",
		Active:      true,
		IsPrimary:   false,
		NIP05Active: true,
		CreatedAt:   time.Now(),
	}
	if s.Username != "bob" {
		t.Error("Username not set")
	}
	if s.IsPrimary {
		t.Error("IsPrimary should be false")
	}
}

// ---------------------------------------------------------------------------
// Primary-reassignment logic (table-driven, no DB)
// ---------------------------------------------------------------------------

// TestPrimaryReassignmentConditions documents when promotion should occur.
func TestPrimaryReassignmentConditions(t *testing.T) {
	type testCase struct {
		name         string
		wasPrimary   bool
		othersCount  int
		shouldPromote bool
	}

	cases := []testCase{
		{"was_primary_with_others", true, 2, true},
		{"was_primary_no_others", true, 0, false},
		{"not_primary_with_others", false, 2, false},
		{"not_primary_no_others", false, 0, false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			// The logic in AdminRevokeAddress:
			//   if wasPrimary && others > 0 { promote }
			shouldPromote := tc.wasPrimary && tc.othersCount > 0
			if shouldPromote != tc.shouldPromote {
				t.Errorf("expected shouldPromote=%v, got %v", tc.shouldPromote, shouldPromote)
			}
		})
	}
}

// TestAliasIsFirstLogic documents the is_primary/nip05_active assignment for new addresses.
func TestAliasIsFirstLogic(t *testing.T) {
	type testCase struct {
		name           string
		existingCount  int
		wantIsPrimary  bool
		wantNIP05Active bool
	}

	cases := []testCase{
		{"first_address", 0, true, true},
		{"second_address_alias", 1, false, false},
		{"third_address_alias", 5, false, false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			isFirst := tc.existingCount == 0
			if isFirst != tc.wantIsPrimary {
				t.Errorf("is_primary: want %v got %v", tc.wantIsPrimary, isFirst)
			}
			if isFirst != tc.wantNIP05Active {
				t.Errorf("nip05_active: want %v got %v", tc.wantNIP05Active, isFirst)
			}
		})
	}
}
